### ISSUE TITLE
build.gradle does not include core/src

### ISSUE THREAD

**Issue by scheibk** [ConnectSDK/Connect-SDK-Android-Lite#1]
I tried including 1.4 of the Connect-SDK-Android-Lite and found a few issues with the build.gradle file.

I had to change the java.srcDirs to 

```
java.srcDir = [
    'src',
    'core/src'
]
```

Also, gradle has changed some names of properties. runProguard is now called minifyEnabled. There was also a change to the dependencies to include 'core/libs'.

I can create a pull request of my build.gradle with some guidance on branching with the Lite project.

**Comment by oleksii-frolov** [comment]
@scheibk Which version of Android Studio do you use?

**Comment by scheibk** [comment]
I just recently upgraded to Android Studio 1.0. It upgraded from beta last week.

**Comment by oleksii-frolov** [comment]
I've updated all build.gradle files for the latest AndroidStudio
